api/urls.py
from django.urls import path, include
from django.conf.urls import url
from api import views
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers
import os
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *

from rest_framework_simplejwt import views as jwt_views

router = routers.SimpleRouter()
router.register(r'cities', CityViewSet)
router.register(r'countries', CountryViewSet)
router.register(r'specialists', SpecialistViewSet)

from rest_framework.authtoken import views as api_views

urlpatterns = [
    url(r'^', include(router.urls)),
]

urlpatterns = format_suffix_patterns(urlpatterns)

main/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name= "main"
urlpatterns = [
    path('', views.Index.as_view(), name='index'), 
    path('specialists', views.Specialists.as_view(), name='specialists'), 
    path('events', views.Events.as_view(), name='events'), 
    path('download/(?P<path>.*)$', views.DownloadFile.as_view(), name="download"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#

oceanswave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from oceanswave.yandex_s3_storage import ClientDocsStorage
from datetime import date
from main.modules.functions import get_str_month

class New(models.Model):
    title = models.TextField(default="")
    description = models.TextField(default="")
    image = models.FileField(storage=ClientDocsStorage(), blank=True, null=True)
    source_link = models.TextField(default="")
    def __str__(self):
        return self.title



class City(models.Model):
    name = models.TextField(default="")

    def __str__(self):
        return self.name

class Country(models.Model):
    country = models.TextField(default="")
    flag = models.FileField(storage=ClientDocsStorage(), blank=True, null=True)
    cities = models.ManyToManyField(City, null=True, blank=True)
    def __str__(self):
        return self.country

class Specialist(models.Model):
    name = models.TextField(default="")
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(default="")
    count_of_lections = models.IntegerField(default=0)
    image = models.FileField(storage=ClientDocsStorage(), blank=True, null=True)
    telegram = models.TextField(default="")
    
    def get_rating_range(self):
        return range(0, int(self.rating))

    def get_cutted_telegram(self):
        return self.telegram.replace("@","")

    def __str__(self):
        return self.name

class Assistant(models.Model):
    name = models.TextField(default="")
    phone = models.TextField(default="")
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.TextField(default="")
    image = models.FileField(storage=ClientDocsStorage(), blank=True, null=True)
    video_url = models.TextField(default="", blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    start_time = models.TimeField(blank=True, null=True)    
    end_time = models.TimeField(blank=True, null=True)    
    teacher = models.TextField(default="", blank=True, null=True)
    price = models.TextField(default="", blank=True, null=True)
    description = models.TextField(default="")
    places_left = models.IntegerField()
    pdf_file = models.FileField(storage=ClientDocsStorage(), blank=True, null=True)
    expired = models.BooleanField(default=False)
    location = models.TextField(default="", blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    assistant = models.ForeignKey(Assistant, on_delete=models.CASCADE, blank=True, null=True)
    def get_expired(self):
        if self.start_date < date.today():
            self.expired = True
            self.save()
        return self.expired

    def ru_date(self):
        month_str = get_str_month(self.start_date.month)
        if self.end_date:
            return str(self.start_date.day) + " - " + str(self.end_date.day) + month_str
        return str(self.start_date.day) + month_str

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.dispatch.dispatcher import receiver
from main.models import *
from main.modules.functions import margin_counter, get_paginated_blogs
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from Bot import Bot
from oceanswave.settings import TELEGRAM
COUNT_SPECIALISTS_ON_PAGE = 9
COUNT_EVENTS_ON_PAGE = 9

class Index(View):
    def get(self, request):
        specialists = Specialist.objects.all()[0:3]
        closest_event = None
        try:
            closest_event = Event.objects.filter(start_date__gte=date.today()).order_by("start_date").first()
        except:
            pass
        news = New.objects.all()[0:4]
        return render(request, "index.html", {
            "specialists": specialists,
            "closest_event": closest_event,
            "news": news,
            "rivers_mobile": range(0, len(specialists) - 1),
            "margin_counter_mobile": margin_counter(-100, 700)
        })
    def post(self, request):
        return render(request, "index.html", {})

class Specialists(View):
    def get(self, request):
        specialists = Specialist.objects.all()
        fake_blocks_count = 0

        country = request.GET.get("country", "")
        city = request.GET.get("city", "")
        rating = request.GET.get("rating", "")

        country_obj = None
        city_obj = None
        cities = None

        if country:
            country_obj = Country.objects.filter(id=country).first()
            if country_obj:
                specialists = specialists.filter(country=country_obj)
        if city:
            city_obj = City.objects.filter(id=city).first()
            if city_obj:
                specialists = specialists.filter(city=city_obj)
        if rating:
            if rating == "true":
                specialists = specialists.order_by("rating")
            elif rating == "false":
                specialists = specialists.order_by("-rating")
        
        if country_obj:
            cities = country_obj.cities.all()

        paginator = Paginator(specialists, COUNT_SPECIALISTS_ON_PAGE)
        paginated_blocks, pages = get_paginated_blogs(request, paginator)

        length = len(paginated_blocks)
        if length % 3 != 0:
            if length % 2 == 0:
                fake_blocks_count = 2
            else:
                fake_blocks_count = 1

        river_count = 0
        river_mobile_count = range(0, length)

        if length > 6:
            river_count = range(0,3)
        elif length > 3:
            river_count = range(0,2)
        elif length > 0:
            river_count = range(0,1)
        else:
            river_count = range(0,0)


        return render(request, "specialists.html", {
            "specialists": paginated_blocks,
            "pages": pages,
            "margin_counter": margin_counter(-800, 700),
            "margin_counter_mobile": margin_counter(-750, 750),
            "river_count": river_count,
            "river_mobile_count": river_mobile_count,
            "fake_blocks_count": range(0, fake_blocks_count),
            "country": country_obj,
            "city": city_obj,
            "rating": rating,
            "countries": Country.objects.all(),
            "cities": cities,
        })
    def post(self, request):
        return render(request, "specialists.html", {})

class Events(View):
    def get(self, request):
        events = Event.objects.all()

        name = request.GET.get("name", "")
        price = request.GET.get("price", "")

        if name and name != "":
            events = events.filter(name__icontains=name)
        if price:
            if price == "true":
                events = events.order_by("price")
            elif price == "false":
                events = events.order_by("-price")

        paginator = Paginator(events, COUNT_EVENTS_ON_PAGE)
        paginated_blocks, pages = get_paginated_blogs(request, paginator)

        length = len(paginated_blocks)
        if length % 3 != 0:
            if length % 2 == 0:
                fake_blocks_count = 2
            else:
                fake_blocks_count = 1

        river_count = 0
        river_mobile_count = range(0, length)

        if length > 6:
            river_count = range(0,3)
        elif length > 3:
            river_count = range(0,2)
        elif length > 0:
            river_count = range(0,1)
        else:
            river_count = range(0,0)


        return render(request, "events.html", {
            "events": paginated_blocks,
            "pages": pages,
            "margin_counter": margin_counter(-1000, 900),
            "margin_counter_mobile": margin_counter(-750, 750),
            "river_count": river_count,
            "river_mobile_count": river_mobile_count,
            "name": name,
            "price": price,
        })
    def post(self, request):
        return render(request, "events.html", {})

class DownloadFile(View):
    def get(self, request):
        fl_path = '/file/path'
        filename = 'downloaded_file_name.extension'

        fl = open(fl_path, 'r')
        mime_type, _ = mimetypes.guess_type(fl_path)
        response = HttpResponse(fl, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response

@receiver(models.signals.post_delete, sender=Specialists)
def specialist_avatar_delete_ondelete(sender, instance, using, **kwargs):
    instance.image.delete(save=False)

@receiver(models.signals.pre_save, sender=Specialists)
def specialist_avatar_delete_onsave(sender, instance, using, **kwargs):
    try:
        old_file = sender.objects.get(pk=instance.pk).image
    except sender.DoesNotExist:
        return False
    
    new_file = instance.image
    if not old_file == new_file:
        old_file.delete(save=False)

@receiver(models.signals.post_delete, sender=Country)
def country_avatar_delete_ondelete(sender, instance, using, **kwargs):
    instance.flag.delete(save=False)

@receiver(models.signals.pre_save, sender=Country)
def country_avatar_delete_onsave(sender, instance, using, **kwargs):
    try:
        old_file = sender.objects.get(pk=instance.pk).flag
    except sender.DoesNotExist:
        return False
    
    new_file = instance.flag
    if not old_file == new_file:
        old_file.delete(save=False)

@receiver(models.signals.post_delete, sender=Event)
def event_avatar_delete_ondelete(sender, instance, using, **kwargs):
    instance.image.delete(save=False)
    instance.pdf_file.delete(save=False)

@receiver(models.signals.pre_save, sender=Event)
def event_avatar_delete_onsave(sender, instance, using, **kwargs):
    try:
        old_file = sender.objects.get(pk=instance.pk).image
    except sender.DoesNotExist:
        return False
    
    new_file = instance.image
    if not old_file == new_file:
        old_file.delete(save=False)

@receiver(models.signals.post_save, sender=Event) 
def when_init(sender, instance, created, **kwargs):
    if created:
        try:
            bot = Bot(TELEGRAM)
            bot.send_event(instance)
        except:
            pass
        

@receiver(models.signals.post_delete, sender=New)
def new_avatar_delete_ondelete(sender, instance, using, **kwargs):
    instance.image.delete(save=False)

@receiver(models.signals.pre_save, sender=New)
def new_avatar_delete_onsave(sender, instance, using, **kwargs):
    try:
        old_file = sender.objects.get(pk=instance.pk).image
    except sender.DoesNotExist:
        return False
    
    new_file = instance.image
    if not old_file == new_file:
        old_file.delete(save=False)

main/templates/base.html
{% load static %}

{% block links %}
    <head>
        <meta property="og:image" content="http://oceans-wave.org/static/img/logo.png"/>                
        <meta property="og:image:secure_url" content="https://oceans-wave.org/static/img/logo.png"/>        
        <meta property="og:image:type" content="image/png" /> 
        <meta property="og:image:width" content="400" /> 
        <meta property="og:image:height" content="400" />
        <script src="{%static 'js/jquery.min.js'%}"></script>
        <script src="{%static 'js/lightslider.js'%}"></script>
        <script src="{%static 'js/slider.js'%}"></script>
        <link rel="stylesheet" href="{%static 'css/lightslider.css'%}">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Oceans Wave</title>
        <link rel="stylesheet" href="{%static 'css/index.css'%}">        
        <link rel="shortcut icon" href="{%static 'img/icon.ico'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'fonts/stylesheet.css'%}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{%static 'rateit/rateit.css'%}">
        <script src="{%static 'rateit/jquery.rateit.js'%}"></script>
        <script src="{%static 'js/functions.js'%}"></script>
        <link rel="stylesheet" type="text/css" href="{%static 'css/pagination.css'%}">
        <style>
            .checked{
                background: linear-gradient(103.4deg, #FFAC30 29.02%, #FFD08B 88.66%);
                -webkit-background-clip: text;
                -moz-background-clip: text;
                -webkit-text-fill-color: transparent; 
                -moz-text-fill-color: transparent;
            }
        </style>
        <script src="{%static 'js/hover.js'%}"></script>
        {% block styles %}

        {% endblock %}
    </head>
{% endblock %}



{% block body%}
    <body>
        {%block telegram%}
            <a href="https://t.me/oceanswavenews" >
                <div class="telegram-block" id="telegram-link">
                    <div class="button">Telegram Канал</div>
                    
                </div>
            </a>
            <div class="close-telegram" id="close-telegram"></div>
        {%endblock%}
        {%block river%}{%endblock%}
        <div class="wrap">
            <div class="header hide-mobile"> 
                <a href="{%url 'main:index'%}">
                    <div class="logos-block">
                        <div class="logo" style="background-image: url({%static 'img/logo.svg'%});"></div>            
                    </div>
                </a>                
                <div class="menu-block">
                    <div class="item scrollto">
                        <a href="/#">
                            <div class="text">Главная</div>
                        </a>                    
                        <div class="item-underline"></div>
                    </div>
                    <div class="item scrollto">
                        <a href="/#about">
                            <div class="text">О нас</div>
                        </a>                    
                        <div class="item-underline"></div>
                    </div>
                    <div class="item scrollto">
                        <a href="/#why">
                            <div class="text">Преимущества</div>
                        </a>                    
                        <div class="item-underline"></div>
                    </div>
                    <div class="item no-margin-right scrollto">
                        <a href="/#specialists">
                            <div class="text">Консультанты</div>
                        </a>
                        
                        <div class="item-underline"></div>
                    </div>                
                </div>
                <a href="{%url 'main:events'%}">
                    <div class="events-button">Список мероприятий</div>
                </a>                
            </div>
    
            <div class="mobile-header show-mobile-flex">            
                <div class="button" id="nav_button" onclick="open_close_Nav()"></div>
                <a href="{%url 'main:index'%}" class="logo">
                    
                </a>                
            </div>
    
            <div class="mobile-menu show-mobile-flex" id="nav">
                    <div class="button" onclick="open_close_Nav()"></div>
                    <div class="menu scrollto">
                        <a href="/#">
                            <div class="item">Главная</div>
                        </a>
                        <a href="/#about">
                            <div class="item">О нас</div>
                        </a>
                        <a href="/#why">
                            <div class="item">Преимущества</div>
                        </a>
                        <a href="/#specialists">
                            <div class="item">Консультанты</div>
                        </a>
                    </div>
                    <div class="pages">
                        <a href="{%url 'main:specialists'%}">
                            <div class="item">Список консультантов</div>
                        </a>
                        <a href="{%url 'main:events'%}">
                            <div class="item">Список мероприятий</div>
                        </a>
                    </div>
                    <div class="social">
                        <a href="https://www.facebook.com/SmartTradeCoin/">
                            <div class="item facebook"></div>
                        </a>
                        <a href="https://twitter.com/SmartTradeCoin">
                            <div class="item twitter"></div>
                        </a>
                        <a href="https://instagram.com/oceans_wave_networking?utm_medium=copy_link">
                            <div class="item instagram"></div>
                        </a>
                        <a href="https://www.youtube.com/channel/UCMByuH8s8YdtA4WkVGidJ-Q">
                            <div class="item youtube"></div>
                        </a>
                        <a href="https://t.me/smarttradecoinofficial">
                            <div class="item telegram"></div>
                        </a>
                    </div>
            </div>
            {%block content%}

            {%endblock%}             
        </div>
    </body>                      
{% endblock %}


{%block footer%}
    <div class="footer hide-mobile">
        <div class="bg"></div>
        <div class="menu scrollto">
            <a href="/#">Главная</a>
            <a href="/#about">О нас</a>
            <a href="/#why">Преимущества</a>
            <a href="/#specialists">Консультанты</a>                
        </div>
        <div class="social">
            <a href="https://www.facebook.com/SmartTradeCoin/">
                <div class="item facebook"></div>
            </a>                
            <a href="https://twitter.com/SmartTradeCoin">
                <div class="item twitter"></div>
            </a>                
            <a href="https://instagram.com/oceans_wave_networking?utm_medium=copy_link">
                <div class="item instagram"></div>
            </a>
            <a href="https://www.youtube.com/channel/UCMByuH8s8YdtA4WkVGidJ-Q">
                <div class="item youtube"></div>
            </a>
            <a href="https://t.me/smarttradecoinofficial">
                <div class="item telegram"></div>
            </a>
        </div>
    </div>
    <div class="mobile-footer show-mobile"></div>
{%endblock%}

<style type="text/css">
    #hellopreloader>p {
    display: none;
    }

    #hellopreloader_preload {
    display: block;
    position: fixed;
    z-index: 99999;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    min-width: 100px;
    background: #F1F2F3 url({%static 'img/preloader.gif'%}) center center no-repeat;
    background-size: 20%;
    }
</style>
<div id="hellopreloader">
    <div id="hellopreloader_preload"></div>
</div>
<script type="text/javascript">
    var hellopreloader = document.getElementById("hellopreloader_preload");

    function fadeOutnojquery(el) {
    el.style.opacity = 1;
    var interhellopreloader = setInterval(function () {
        el.style.opacity = el.style.opacity - 0.05;
        if (el.style.opacity <= 0.05) {
        clearInterval(interhellopreloader);
        hellopreloader.style.display = "none";
        document.getElementsByTagName("html")[0].style.overflow = "";
        }
    }, 16);
    }
    window.onload = function () {


    setTimeout(function () {
        fadeOutnojquery(hellopreloader);
    }, 100);
    };

</script>

{%block scripts%}
{%endblock%}

main/templates/specialists.html
{% extends "base.html" %}
{%load static%}

{%block styles%}
    <script src="{%static 'js/custom-select.js'%}"></script>
    {%if not specialists%}
        <style>
            .wrap{
                height: -webkit-fill-available;
            }
        </style>
    {%endif%}
    <style>
        @media(max-width: 900px){
            .specialists-block{
                margin-top: 50px !important;
            }
        }
    </style>
{%endblock%}

{%block content%}

    <div class="sort-block">
        <div class="title hide-mobile">Сортировка</div>
        <div class="sorts">
            <label class="select" style="width: 25%;">                
                <select class="sort-quests" onchange="location = this.value;">
                    <option selected value="?country=&rating={{rating}}">Страна</option>
                    {% for current_country in countries%}
                        <option {%if country.id == current_country.id %} selected {%endif%} value="?country={{current_country.id}}&rating={{rating}}">{{current_country.country}}</option>
                    {%endfor%}
                </select>
            </label>
            
            {%if country and country != ''%}
                <label class="select" style="width: 25%;">                
                    <select class="sort-quests" onchange="location = this.value;">                        
                        <option selected value="?country={{country.id}}&city=&rating={{rating}}">Город</option>
                        {%for current_city in cities%}
                            <option {%if city.id == current_city.id %} selected {%endif%} value="?country={{country.id}}&city={{current_city.id}}&rating={{rating}}">{{current_city.name}}</option>
                        {%endfor%}
                    </select>
                </label>             
            {%endif%}
            <label class="select" style="width: 25%;">                
                <select class="sort-quests" onchange="location = this.value;">   
                    <option selected  value="?country={{country.id}}&city={{city.id}}&rating=">Рейтинг</option>                                         
                    <option {%if rating == 'true' %} selected {%endif%} value="?country={{country.id}}&city={{city.id}}&rating=true">По возрастанию</option>
                    <option {%if rating == 'false' %} selected {%endif%} value="?country={{country.id}}&city={{city.id}}&rating=false">По убыванию</option>
                </select>
            </label>  
                
        </div>
    </div>
    {%if specialists%}
        <div class="specialists-block" id="specialists">
            {%for river in river_count %}
                {% if forloop.counter|divisibleby:2 %}
                    <div class="river3 hide-mobile second" style="top: {{margin_counter.inc}}px;"></div>
                {%else%}                    
                    <div class="river3 hide-mobile first" style="top: {{margin_counter.inc}}px;"></div>
                {%endif%}                        
            {%endfor%}

            {%for river in river_mobile_count%}            
                <div class="river3 show-mobile" style="top: {{margin_counter_mobile.inc}}px;"></div>
            {%endfor%}
            
            
            
            <div class="specialists">
                {%for specialist in specialists %}
                    <div class="specialist-wrap margin">
                        <div class="bg"></div>
                        <div class="specialist-block">
                            
                            <div class="avatar" style="background-image: url({{specialist.image.url}});"></div>

                            <div class="name">{{specialist.name}}</div>

                            <div class="rating">
                                <div class="rateit" data-rateit-value="{{specialist.rating}}" data-rateit-ispreset="true" data-rateit-readonly="true" data-rateit-mode="font"  style="font-size:35px"></div>
                            </div>

                            <div class="country-block">
                                <div class="flag" style="background-image: url({{specialist.country.flag.url}});"></div>
                                <div class="country">{{specialist.country.country}}, {{specialist.city.name}}</div>
                            </div>

                            <div class="description">{{specialist.description}}

Telegram: <a style="color: blue !important;" href="https://t.me/{{specialist.get_cutted_telegram}}">{{specialist.telegram}}</a></div>
                            <div class="lections">
                                Проведено лекций: {{specialist.count_of_lections}}
                            </div>
                        </div>
                    </div>
                {%endfor%}
                {% for block in fake_blocks_count %}
                    <div class="specialist-wrap-fake hide-mobile"></div>
                {%endfor%}
            </div>
            {% if pages|length > 1%}
                <div class="navigation">
                    <ul>
                        {% for page in pages%}
                            {% if page == specialists.number %}
                                <li class="page-current">
                                    <span>{{page}}</span>
                                </li>
                            {% else %}
                                <li class="page-nav">
                                    <a href="?country={{country.id}}&city={{city.id}}&rating={{rating}}&page={{page}}"> {{page}} </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {%endif%}
        </div>
    {%else%}
        <div class="no-found-block">Ничего не найдено!</div>
    {%endif%}
    
{%endblock%}

main/templates/telegram_message.html
<strong>{{event.name}}</strong>

<strong>Время: </strong> {{event.ru_date}} {%if event.start_time and event.end_time%}с {{ event.start_time|date:'H:i' }} до {{ event.end_time|date:'H:i' }}{%endif%}
<strong>Место проведения: </strong> {{event.location}}
<strong>Страна: </strong> {{event.country.country}}
<strong>Цена: </strong> {{event.price}}тг
<strong>Лектор: </strong> {{event.teacher}}
<strong>Осталось мест: </strong> {{event.places_left}}

{{ event.description }}

https://oceans-wave.org/